"""ajust tables resident

Revision ID: 23c99c835f92
Revises: c9bea5562ac4
Create Date: 2025-11-27 15:42:29.980744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c99c835f92'
down_revision: Union[str, Sequence[str], None] = 'c9bea5562ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('cns', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('nome_social', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', name='sexoenum'), nullable=False),
    sa.Column('raca_cor', sa.Enum('BRANCA', 'PRETA', 'PARDA', 'AMARELA', 'INDIGENA', name='racacorenum'), nullable=False),
    sa.Column('etnia', sa.String(), nullable=True),
    sa.Column('nis_pis_pasep', sa.String(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('mae_desconhecida', sa.Boolean(), nullable=True),
    sa.Column('nome_pai', sa.String(), nullable=True),
    sa.Column('pai_desconhecido', sa.Boolean(), nullable=True),
    sa.Column('nacionalidade', sa.Enum('BRASILEIRA', 'NATURALIZADO', 'ESTRANGEIRO', name='nacionalidadeenum'), nullable=False),
    sa.Column('pais_nascimento', sa.String(), nullable=True),
    sa.Column('dt_naturalizacao', sa.Date(), nullable=True),
    sa.Column('portaria_naturalizacao', sa.String(), nullable=True),
    sa.Column('municipio_nascimento', sa.String(), nullable=True),
    sa.Column('telefone_celular', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('eh_responsavel_familiar', sa.Boolean(), nullable=True),
    sa.Column('cns_cpf_responsavel', sa.String(), nullable=True),
    sa.Column('relacao_parentesco', sa.Enum('CONJUGE_COMPANHEIRO', 'FILHO', 'ENTEADO', 'NETO_BISNETO', 'PAI_MAE', 'SOGRO', 'IRMAO_IRMA', 'GENRO_NORA', 'OUTRO_PARENTE', 'NAO_PARENTE', name='grauparentescoenum'), nullable=True),
    sa.Column('ocupacao', sa.String(), nullable=True),
    sa.Column('frequenta_escola', sa.Boolean(), nullable=True),
    sa.Column('escolaridade', sa.Enum('CRECHE', 'PRE_ESCOLA', 'ALFABETIZACAO', 'FUNDAMENTAL_1_4', 'FUNDAMENTAL_5_8', 'FUNDAMENTAL_COMPLETO', 'EJA_INICIAIS', 'EJA_FINAIS', 'MEDIO', 'MEDIO_EJA', 'SUPERIOR', 'NENHUM', name='escolaridadeenum'), nullable=True),
    sa.Column('situacao_mercado', sa.Enum('EMPREGADOR', 'ASSALARIADO_COM_CARTEIRA', 'ASSALARIADO_SEM_CARTEIRA', 'AUTONOMO_COM_PREVIDENCIA', 'AUTONOMO_SEM_PREVIDENCIA', 'APOSENTADO_PENSIONISTA', 'DESEMPREGADO', 'NAO_TRABALHA', 'SERVIDOR_PUBLICO', 'OUTRO', name='situacaomercadoenum'), nullable=True),
    sa.Column('responsavel_crianca', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('frequenta_cuidador', sa.Boolean(), nullable=True),
    sa.Column('participa_grupos_comunitarios', sa.Boolean(), nullable=True),
    sa.Column('possui_plano_saude', sa.Boolean(), nullable=True),
    sa.Column('membro_povo_tradicional', sa.Boolean(), nullable=True),
    sa.Column('povo_tradicional_desc', sa.String(), nullable=True),
    sa.Column('orientacao_sexual', sa.Enum('HETEROSSEXUAL', 'GAY', 'LESBICA', 'BISSEXUAL', 'OUTRO', name='orientacaosexualenum'), nullable=True),
    sa.Column('identidade_genero', sa.Enum('HOMEM_TRANSEXUAL', 'MULHER_TRANSEXUAL', 'TRAVESTI', 'OUTRO', name='identidadegeneroenum'), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=True),
    sa.Column('deficiencias_tipo', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('saida_cadastro', sa.Boolean(), nullable=True),
    sa.Column('motivo_saida', sa.String(), nullable=True),
    sa.Column('data_obito', sa.Date(), nullable=True),
    sa.Column('numero_do', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['residence_id'], ['residence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_residents_id'), 'residents', ['id'], unique=False)
    op.alter_column('visits', 'resident_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'visits', 'residents', ['resident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.alter_column('visits', 'resident_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_residents_id'), table_name='residents')
    op.drop_table('residents')
    # ### end Alembic commands ###
