"""remove 3 types of other situation in healthsituation table

Revision ID: 450ec7d3c702
Revises: f8ac2f617694
Create Date: 2025-11-30 23:41:20.636039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '450ec7d3c702'
down_revision: Union[str, Sequence[str], None] = 'f8ac2f617694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_situations', sa.Column('outras_condicoes', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('health_situations', 'outras_condicoes_2')
    op.drop_column('health_situations', 'outras_condicoes_1')
    op.drop_column('health_situations', 'outras_condicoes_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_situations', sa.Column('outras_condicoes_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('health_situations', sa.Column('outras_condicoes_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('health_situations', sa.Column('outras_condicoes_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('health_situations', 'outras_condicoes')
    # ### end Alembic commands ###
