"""ajust relationship between visit and healthsituation

Revision ID: 48ba7783bc84
Revises: bb0b904a83ad
Create Date: 2025-11-28 01:23:17.521636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48ba7783bc84'
down_revision: Union[str, Sequence[str], None] = 'bb0b904a83ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.add_column('health_situations', sa.Column('visit_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'health_situations', ['visit_id'])
    op.create_foreign_key(None, 'health_situations', 'visits', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_situations', type_='foreignkey')
    op.drop_constraint(None, 'health_situations', type_='unique')
    op.drop_column('health_situations', 'visit_id')
    op.create_table('user_role',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('user_role_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_role_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_role_pkey'))
    )
    # ### end Alembic commands ###
