"""create health_situation table

Revision ID: 854b3f022234
Revises: 23c99c835f92
Create Date: 2025-11-27 16:38:18.039695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '854b3f022234'
down_revision: Union[str, Sequence[str], None] = '23c99c835f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_situations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('esta_gestante', sa.Boolean(), nullable=True),
    sa.Column('maternidade_referencia', sa.String(), nullable=True),
    sa.Column('peso_situacao', sa.Enum('abaixo_do_peso', 'peso_adequado', 'acima_do_peso', name='pesosituacaoenum'), nullable=True),
    sa.Column('esta_fumante', sa.Boolean(), nullable=True),
    sa.Column('usa_alcool', sa.Boolean(), nullable=True),
    sa.Column('usa_outras_drogas', sa.Boolean(), nullable=True),
    sa.Column('tem_hipertensao', sa.Boolean(), nullable=True),
    sa.Column('tem_diabetes', sa.Boolean(), nullable=True),
    sa.Column('teve_avc_derrame', sa.Boolean(), nullable=True),
    sa.Column('teve_infarto', sa.Boolean(), nullable=True),
    sa.Column('tem_doenca_cardiaca', sa.Boolean(), nullable=True),
    sa.Column('doencas_cardiacas_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_problemas_rins', sa.Boolean(), nullable=True),
    sa.Column('problemas_rins_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_doenca_respiratoria', sa.Boolean(), nullable=True),
    sa.Column('doenca_respiratoria_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_hanseniase', sa.Boolean(), nullable=True),
    sa.Column('tem_tuberculose', sa.Boolean(), nullable=True),
    sa.Column('tem_cancer', sa.Boolean(), nullable=True),
    sa.Column('internacao_ultimos_12_meses', sa.Boolean(), nullable=True),
    sa.Column('causa_internacao', sa.String(), nullable=True),
    sa.Column('diagnostico_problema_mental', sa.Boolean(), nullable=True),
    sa.Column('esta_acamado', sa.Boolean(), nullable=True),
    sa.Column('esta_domiciliado', sa.Boolean(), nullable=True),
    sa.Column('usa_plantas_medicinais', sa.Boolean(), nullable=True),
    sa.Column('plantas_medicinais_desc', sa.String(), nullable=True),
    sa.Column('usa_praticas_integrativas', sa.Boolean(), nullable=True),
    sa.Column('outras_condicoes_1', sa.String(), nullable=True),
    sa.Column('outras_condicoes_2', sa.String(), nullable=True),
    sa.Column('outras_condicoes_3', sa.String(), nullable=True),
    sa.Column('em_situacao_rua', sa.Boolean(), nullable=True),
    sa.Column('tempo_situacao_rua', sa.Enum('menos_6_meses', 'de_6_a_12_meses', 'de_1_a_5_anos', 'mais_5_anos', name='temposituacaoruaenum'), nullable=True),
    sa.Column('recebe_beneficio', sa.Boolean(), nullable=True),
    sa.Column('possui_referencia_familiar', sa.Boolean(), nullable=True),
    sa.Column('visita_familiar_frequente', sa.Boolean(), nullable=True),
    sa.Column('grau_parentesco_referencia', sa.String(), nullable=True),
    sa.Column('acompanhado_outra_instituicao', sa.Boolean(), nullable=True),
    sa.Column('instituicao_acompanhamento', sa.String(), nullable=True),
    sa.Column('frequencia_alimentacao', sa.Enum('uma_vez', 'duas_ou_tres_vezes', 'mais_de_tres_vezes', name='frequenciaalimentacaoenum'), nullable=True),
    sa.Column('origem_alimentacao', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_acesso_higiene_pessoal', sa.Boolean(), nullable=True),
    sa.Column('higiene_pessoal_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id')
    )
    op.create_index(op.f('ix_health_situations_id'), 'health_situations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_situations_id'), table_name='health_situations')
    op.drop_table('health_situations')
    # ### end Alembic commands ###
