"""remove form, questions and answer table

Revision ID: bb0b904a83ad
Revises: 854b3f022234
Create Date: 2025-11-27 17:12:44.858452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb0b904a83ad'
down_revision: Union[str, Sequence[str], None] = '854b3f022234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.add_column('users', sa.Column('cns', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cnes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ine', sa.String(), nullable=True))
    op.drop_column('visits', 'form_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'ine')
    op.drop_column('users', 'cnes')
    op.drop_column('users', 'cns')
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('answers_visit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('answers_pkey'))
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###
