"""initial_deploy_v1

Revision ID: bca100a5f49f
Revises: 
Create Date: 2025-12-13 22:55:08.200880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca100a5f49f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cns', sa.String(), nullable=True),
    sa.Column('cnes', sa.String(), nullable=True),
    sa.Column('ine', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_geospatial_table('residence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('tipo_logradouro', sa.String(), nullable=False),
    sa.Column('nome_logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('sem_numero', sa.Boolean(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('ponto_referencia', sa.String(), nullable=True),
    sa.Column('microarea', sa.String(), nullable=False),
    sa.Column('fora_de_area', sa.Boolean(), nullable=True),
    sa.Column('telefone_residencia', sa.String(), nullable=True),
    sa.Column('telefone_contato', sa.String(), nullable=True),
    sa.Column('tipo_imovel', sa.Enum('DOMICILIO', 'COMERCIO', 'TERRENO_BALDIO', 'PONTO_ESTRATEGICO', 'ESCOLA', 'CRECHE', 'ABRIGO', 'ILPI', 'UNIDADE_PRISIONAL', 'MEDIDA_SOCIOEDUCATIVA', 'DELEGACIA', 'ESTABELECIMENTO_RELIGIOSO', 'OUTROS', name='imovelenum'), nullable=False),
    sa.Column('situacao_moradia', sa.Enum('PROPRIO', 'FINANCIADO', 'ALUGADO', 'ARRENDADO', 'CEDIDO', 'OCUPACAO', 'SITUACAO_RUA', 'OUTRA', name='situacaomoradiaenum'), nullable=False),
    sa.Column('tipo_domicilio', sa.Enum('CASA', 'APARTAMENTO', 'COMODO', 'OUTRO', name='domicilioenum'), nullable=False),
    sa.Column('numero_moradores', sa.Integer(), nullable=False),
    sa.Column('numero_comodos', sa.Integer(), nullable=False),
    sa.Column('material_paredes', sa.Enum('ALVENARIA', 'TAIPA', 'MADEIRA', 'MATERIAL_APROVEITADO', 'PALHA', 'OUTRO', name='materialparedesenum'), nullable=False),
    sa.Column('revestimento_parede', sa.Boolean(), nullable=False),
    sa.Column('tipo_acesso', sa.Enum('RUA_PAVIMENTADA', 'CHAO_BATIDO', 'FLUVIAL', 'OUTRO', name='acessoenum'), nullable=False),
    sa.Column('disponibilidade_energia', sa.Boolean(), nullable=False),
    sa.Column('abastecimento_agua', sa.Enum('REDE_ENCANADA', 'POCO_NASCENTE', 'CISTERNA', 'CARRO_PIPA', 'OUTRO', name='abastecimentoaguaenum'), nullable=False),
    sa.Column('tratamento_agua', sa.Enum('FILTRADA', 'FERVIDA', 'CLORADA', 'MINERAL', 'SEM_TRATAMENTO', name='tratamentoaguaenum'), nullable=False),
    sa.Column('escoamento_sanitario', sa.Enum('REDE', 'FOSSA_SEPTICA', 'FOSSA_RUDIMENTAR', 'DIRETO_RIO', 'CEU_ABERTO', 'OUTRA', name='escoamentosanitarioenum'), nullable=False),
    sa.Column('destino_lixo', sa.Enum('COLETADO', 'QUEIMADO_ENTERRADO', 'CEU_ABERTO', 'OUTRO', name='destinolixoenum'), nullable=False),
    sa.Column('possui_animais', sa.Boolean(), nullable=False),
    sa.Column('animais_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('quantidade_animais', sa.Integer(), nullable=True),
    sa.Column('condicao_posse_terra', sa.Enum('PROPRIETARIO', 'PARCEIRO_MEEIRO', 'ASSENTADO', 'POSSEIRO', 'ARRENDATARIO', 'COMODATARIO', 'BENEFICIARIO_BANCO_TERRA', 'NAO_SE_APLICA', name='posseterraenum'), nullable=True),
    sa.Column('geo_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_residence_geo_location', 'residence', ['geo_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_residence_id'), 'residence', ['id'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('cns', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('nome_social', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', name='sexoenum'), nullable=False),
    sa.Column('raca_cor', sa.Enum('BRANCA', 'PRETA', 'PARDA', 'AMARELA', 'INDIGENA', name='racacorenum'), nullable=False),
    sa.Column('etnia', sa.String(), nullable=True),
    sa.Column('nis_pis_pasep', sa.String(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('mae_desconhecida', sa.Boolean(), nullable=True),
    sa.Column('nome_pai', sa.String(), nullable=True),
    sa.Column('pai_desconhecido', sa.Boolean(), nullable=True),
    sa.Column('nacionalidade', sa.Enum('BRASILEIRA', 'NATURALIZADO', 'ESTRANGEIRO', name='nacionalidadeenum'), nullable=False),
    sa.Column('pais_nascimento', sa.String(), nullable=True),
    sa.Column('dt_naturalizacao', sa.Date(), nullable=True),
    sa.Column('portaria_naturalizacao', sa.String(), nullable=True),
    sa.Column('municipio_nascimento', sa.String(), nullable=True),
    sa.Column('telefone_celular', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('eh_responsavel_familiar', sa.Boolean(), nullable=True),
    sa.Column('cns_cpf_responsavel', sa.String(), nullable=True),
    sa.Column('relacao_parentesco', sa.Enum('CONJUGE_COMPANHEIRO', 'FILHO', 'ENTEADO', 'NETO_BISNETO', 'PAI_MAE', 'SOGRO', 'IRMAO_IRMA', 'GENRO_NORA', 'OUTRO_PARENTE', 'NAO_PARENTE', name='grauparentescoenum'), nullable=True),
    sa.Column('ocupacao', sa.String(), nullable=True),
    sa.Column('frequenta_escola', sa.Boolean(), nullable=True),
    sa.Column('escolaridade', sa.Enum('CRECHE', 'PRE_ESCOLA', 'CLASSE_ALFABETIZACAO', 'FUNDAMENTAL_1_4', 'FUNDAMENTAL_5_8', 'FUNDAMENTAL_COMPLETO', 'FUNDAMENTAL_ESPECIAL', 'EJA_INICIAIS', 'EJA_FINAIS', 'MEDIO', 'MEDIO_ESPECIAL', 'MEDIO_EJA', 'SUPERIOR', 'ALFABETIZACAO_ADULTOS', 'NENHUM', name='escolaridadeenum'), nullable=True),
    sa.Column('situacao_mercado', sa.Enum('EMPREGADOR', 'ASSALARIADO_COM_CARTEIRA', 'ASSALARIADO_SEM_CARTEIRA', 'AUTONOMO_COM_PREVIDENCIA', 'AUTONOMO_SEM_PREVIDENCIA', 'APOSENTADO_PENSIONISTA', 'DESEMPREGADO', 'NAO_TRABALHA', 'SERVIDOR_PUBLICO', 'OUTRO', name='situacaomercadoenum'), nullable=True),
    sa.Column('responsavel_crianca', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('frequenta_cuidador', sa.Boolean(), nullable=True),
    sa.Column('participa_grupos_comunitarios', sa.Boolean(), nullable=True),
    sa.Column('possui_plano_saude', sa.Boolean(), nullable=True),
    sa.Column('membro_povo_tradicional', sa.Boolean(), nullable=True),
    sa.Column('povo_tradicional_desc', sa.String(), nullable=True),
    sa.Column('orientacao_sexual', sa.Enum('HETEROSSEXUAL', 'GAY', 'LESBICA', 'BISSEXUAL', 'OUTRO', name='orientacaosexualenum'), nullable=True),
    sa.Column('identidade_genero', sa.Enum('HOMEM_TRANSEXUAL', 'MULHER_TRANSEXUAL', 'TRAVESTI', 'OUTRO', name='identidadegeneroenum'), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=True),
    sa.Column('deficiencias_tipo', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('saida_cadastro', sa.Boolean(), nullable=True),
    sa.Column('motivo_saida', sa.String(), nullable=True),
    sa.Column('data_obito', sa.Date(), nullable=True),
    sa.Column('numero_do', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['residence_id'], ['residence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_residents_id'), 'residents', ['id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('data_visita', sa.DateTime(), nullable=True),
    sa.Column('desfecho', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_table('health_situations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('esta_gestante', sa.Boolean(), nullable=True),
    sa.Column('maternidade_referencia', sa.String(), nullable=True),
    sa.Column('peso_situacao', sa.Enum('abaixo_do_peso', 'peso_adequado', 'acima_do_peso', name='pesosituacaoenum'), nullable=True),
    sa.Column('esta_fumante', sa.Boolean(), nullable=True),
    sa.Column('usa_alcool', sa.Boolean(), nullable=True),
    sa.Column('usa_outras_drogas', sa.Boolean(), nullable=True),
    sa.Column('tem_hipertensao', sa.Boolean(), nullable=True),
    sa.Column('tem_diabetes', sa.Boolean(), nullable=True),
    sa.Column('teve_avc_derrame', sa.Boolean(), nullable=True),
    sa.Column('teve_infarto', sa.Boolean(), nullable=True),
    sa.Column('tem_doenca_cardiaca', sa.Boolean(), nullable=True),
    sa.Column('doencas_cardiacas_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_problemas_rins', sa.Boolean(), nullable=True),
    sa.Column('problemas_rins_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_doenca_respiratoria', sa.Boolean(), nullable=True),
    sa.Column('doenca_respiratoria_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_hanseniase', sa.Boolean(), nullable=True),
    sa.Column('tem_tuberculose', sa.Boolean(), nullable=True),
    sa.Column('tem_cancer', sa.Boolean(), nullable=True),
    sa.Column('internacao_ultimos_12_meses', sa.Boolean(), nullable=True),
    sa.Column('causa_internacao', sa.String(), nullable=True),
    sa.Column('diagnostico_problema_mental', sa.Boolean(), nullable=True),
    sa.Column('esta_acamado', sa.Boolean(), nullable=True),
    sa.Column('esta_domiciliado', sa.Boolean(), nullable=True),
    sa.Column('usa_plantas_medicinais', sa.Boolean(), nullable=True),
    sa.Column('plantas_medicinais_desc', sa.String(), nullable=True),
    sa.Column('usa_praticas_integrativas', sa.Boolean(), nullable=True),
    sa.Column('outras_condicoes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('em_situacao_rua', sa.Boolean(), nullable=True),
    sa.Column('tempo_situacao_rua', sa.Enum('menos_6_meses', 'de_6_a_12_meses', 'de_1_a_5_anos', 'mais_5_anos', name='temposituacaoruaenum'), nullable=True),
    sa.Column('recebe_beneficio', sa.Boolean(), nullable=True),
    sa.Column('possui_referencia_familiar', sa.Boolean(), nullable=True),
    sa.Column('visita_familiar_frequente', sa.Boolean(), nullable=True),
    sa.Column('grau_parentesco_referencia', sa.String(), nullable=True),
    sa.Column('acompanhado_outra_instituicao', sa.Boolean(), nullable=True),
    sa.Column('instituicao_acompanhamento', sa.String(), nullable=True),
    sa.Column('frequencia_alimentacao', sa.Enum('uma_vez', 'duas_ou_tres_vezes', 'mais_de_tres_vezes', name='frequenciaalimentacaoenum'), nullable=True),
    sa.Column('origem_alimentacao', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tem_acesso_higiene_pessoal', sa.Boolean(), nullable=True),
    sa.Column('higiene_pessoal_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index(op.f('ix_health_situations_id'), 'health_situations', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_situations_id'), table_name='health_situations')
    op.drop_table('health_situations')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_residents_id'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_residence_id'), table_name='residence')
    op.drop_geospatial_index('idx_residence_geo_location', table_name='residence', postgresql_using='gist', column_name='geo_location')
    op.drop_geospatial_table('residence')
    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
