"""ajust tables resident and residence

Revision ID: c9bea5562ac4
Revises: 08d280663c4c
Create Date: 2025-11-27 14:27:00.643176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bea5562ac4'
down_revision: Union[str, Sequence[str], None] = '08d280663c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'residence', 'users', ['responsavel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residence', type_='foreignkey')
    # ### end Alembic commands ###
