"""ajust id and visit_id unique in healthsituation table

Revision ID: ec6361ba3967
Revises: e76c15a190a5
Create Date: 2025-11-28 01:57:29.209301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6361ba3967'
down_revision: Union[str, Sequence[str], None] = 'e76c15a190a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('health_situations_resident_id_key'), 'health_situations', type_='unique')
    op.drop_index(op.f('ix_health_situations_id'), table_name='health_situations')
    op.create_index(op.f('ix_health_situations_id'), 'health_situations', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_situations_id'), table_name='health_situations')
    op.create_index(op.f('ix_health_situations_id'), 'health_situations', ['id'], unique=False)
    op.create_unique_constraint(op.f('health_situations_resident_id_key'), 'health_situations', ['resident_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
