"""refactor(residencie): recreate residencie model

Revision ID: f7c6e61e78c3
Revises: 9f626cfbf9cd
Create Date: 2025-11-27 02:40:34.735109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7c6e61e78c3'
down_revision: Union[str, Sequence[str], None] = '9f626cfbf9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('residence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('tipo_logradouro', sa.String(), nullable=False),
    sa.Column('nome_logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('sem_numero', sa.Boolean(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('ponto_referencia', sa.String(), nullable=True),
    sa.Column('microarea', sa.String(), nullable=False),
    sa.Column('fora_de_area', sa.Boolean(), nullable=True),
    sa.Column('telefone_residencia', sa.String(), nullable=True),
    sa.Column('telefone_contato', sa.String(), nullable=True),
    sa.Column('tipo_imovel', sa.Enum('DOMICILIO', 'COMERCIO', 'TERRENO_BALDIO', 'PONTO_ESTRATEGICO', 'ESCOLA', 'CRECHE', 'ABRIGO', 'ILPI', 'UNIDADE_PRISIONAL', 'MEDIDA_SOCIOEDUCATIVA', 'DELEGACIA', 'ESTABELECIMENTO_RELIGIOSO', 'OUTROS', name='imovelenum'), nullable=False),
    sa.Column('situacao_moradia', sa.Enum('PROPRIO', 'FINANCIADO', 'ALUGADO', 'ARRENDADO', 'CEDIDO', 'OCUPACAO', 'SITUACAO_RUA', 'OUTRA', name='situacaomoradiaenum'), nullable=False),
    sa.Column('tipo_domicilio', sa.Enum('CASA', 'APARTAMENTO', 'COMODO', 'OUTRO', name='domicilioenum'), nullable=False),
    sa.Column('numero_moradores', sa.Integer(), nullable=False),
    sa.Column('numero_comodos', sa.Integer(), nullable=False),
    sa.Column('material_paredes', sa.Enum('ALVENARIA', 'TAIPA', 'MADEIRA', 'MATERIAL_APROVEITADO', 'PALHA', 'OUTRO', name='materialparedesenum'), nullable=False),
    sa.Column('revestimento_parede', sa.Boolean(), nullable=False),
    sa.Column('tipo_acesso', sa.Enum('RUA_PAVIMENTADA', 'CHAO_BATIDO', 'FLUVIAL', 'OUTRO', name='acessoenum'), nullable=False),
    sa.Column('disponibilidade_energia', sa.Boolean(), nullable=False),
    sa.Column('abastecimento_agua', sa.Enum('REDE_ENCANADA', 'POCO_NASCENTE', 'CISTERNA', 'CARRO_PIPA', 'OUTRO', name='abastecimentoaguaenum'), nullable=False),
    sa.Column('tratamento_agua', sa.Enum('FILTRADA', 'FERVIDA', 'CLORADA', 'MINERAL', 'SEM_TRATAMENTO', name='tratamentoaguaenum'), nullable=False),
    sa.Column('escoamento_sanitario', sa.Enum('REDE', 'FOSSA_SEPTICA', 'FOSSA_RUDIMENTAR', 'DIRETO_RIO', 'CEU_ABERTO', 'OUTRA', name='escoamentosanitarioenum'), nullable=False),
    sa.Column('destino_lixo', sa.Enum('COLETADO', 'QUEIMADO_ENTERRADO', 'CEU_ABERTO', 'OUTRO', name='destinolixoenum'), nullable=False),
    sa.Column('possui_animais', sa.Boolean(), nullable=False),
    sa.Column('animais_tipos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('quantidade_animais', sa.Integer(), nullable=True),
    sa.Column('condicao_posse_terra', sa.Enum('PROPRIETARIO', 'PARCEIRO_MEEIRO', 'ASSENTADO', 'POSSEIRO', 'ARRENDATARIO', 'COMODATARIO', 'BENEFICIARIO_BANCO_TERRA', 'NAO_SE_APLICA', name='posseterraenum'), nullable=True),
    sa.Column('geo_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_residence_geo_location', 'residence', ['geo_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_residence_id'), 'residence', ['id'], unique=False)
    op.create_foreign_key(None, 'residents', 'residence', ['residence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residents', type_='foreignkey')
    op.drop_index(op.f('ix_residence_id'), table_name='residence')
    op.drop_geospatial_index('idx_residence_geo_location', table_name='residence', postgresql_using='gist', column_name='geo_location')
    op.drop_geospatial_table('residence')
    # ### end Alembic commands ###
