"""ajust visit table

Revision ID: f8ac2f617694
Revises: ec6361ba3967
Create Date: 2025-11-29 18:17:29.066675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8ac2f617694'
down_revision: Union[str, Sequence[str], None] = 'ec6361ba3967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('data_visita', sa.DateTime(), nullable=True))
    op.add_column('visits', sa.Column('desfecho', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('observacoes', sa.String(), nullable=True))
    op.drop_column('visits', 'visit_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('visits', 'observacoes')
    op.drop_column('visits', 'desfecho')
    op.drop_column('visits', 'data_visita')
    # ### end Alembic commands ###
